# Generated by Django 5.0.4 on 2024-05-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumeperfumeprice',
            name='volume',
            field=models.CharField(max_length=300, verbose_name='حجم عطر'),
        ),
    ]
