# Generated by Django 5.0.4 on 2024-05-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_volumeperfumeprice_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='mil_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت هر میل'),
        ),
    ]
