# Generated by Django 5.0.4 on 2024-05-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shop', '0003_perfume_mil_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='volume',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, to='shop.volumeperfumeprice', verbose_name='حجم محصول'),
            preserve_default=False,
        ),
    ]
