# Generated by Django 5.0.4 on 2024-05-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_orderdetail_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نوع ارسال')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت ارسال')),
            ],
            options={
                'verbose_name': 'شیوه ارسال',
                'verbose_name_plural': 'شیوه های ارسال',
            },
        ),
    ]
