# Generated by Django 5.0.4 on 2024-06-03 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_shippingprice_shippingmethod_and_more'),
        ('shop', '0004_alter_volumeperfumeprice_perfume_perfumevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.perfume'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.volumeperfumeprice'),
        ),
    ]
